version: "3.8"

services:
  # Service Spring MVC
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/pvz
      - SPRING_DATASOURCE_USERNAME=hugo
      - SPRING_DATASOURCE_PASSWORD=admin
    container_name: pvz
    volumes:
      - .:/src

  # Service pour MySQL
  mysql:
    image: mysql:8.0
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "3307:3306"
    container_name: mysql-db
    volumes:
      - mysql-data:/var/lib/mysql
      - ./pvz.sql:/docker-entrypoint-initdb.d/pvz.sql

  # Service Frontend
  front-pvz:
    build:
      context: ./front_pvz
    working_dir: /front_pvz
    command: bun dev
    ports:
      - "5173:5173"
    volumes:
      - ./front_pvz:/front_pvz
    depends_on:
      - app
    container_name: front-pvz

volumes:
  mysql-data:
