version: "3.8"

services:
  # Service pour ton application Spring MVC
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/pvz
      - SPRING_DATASOURCE_USERNAME=hugo
      - SPRING_DATASOURCE_PASSWORD=admin
    container_name: pvz
    volumes:
      - .:/src

  # Service pour la base de données MySQL
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pvz
      MYSQL_USER: hugo
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    container_name: mysql-db
    volumes:
      - mysql-data:/var/lib/mysql
      - ./pvz.sql:/docker-entrypoint-initdb.d/pvz.sql

volumes:
  mysql-data:
